services:
  - type: web
    name: roadalert-backend
    env: node
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    plan: free
    branch: main
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000